version: '3.8'

services:

  frontend:
    build: ./frontend
    container_name: fillytrckr-frontend
    ports:
      - "3006:80"
    networks:
      - fillytrckr_network
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: fillytrckr-backend
    ports:
      - "3007:8000"
    environment:
      - DB_TYPE=${DB_TYPE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - TZ=${TZ}
    networks:
      - fillytrckr_network
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: fillytrckr-postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fillytrckr_network

volumes:
  postgres_data:

networks:
  fillytrckr_network:
    driver: bridge
